'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8000.
'
Namespace xoService
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="xotestSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class xotest
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://mixco19/xoService/xotest.asmx"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoTestConn", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoTestConn() As String
            Dim results() As Object = Me.Invoke("xoTestConn", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginxoTestConn(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoTestConn", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoTestConn(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoExportar", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoExportar(ByVal dsxo As System.Data.DataSet, ByRef res As String, ByVal pruta As String, ByVal psociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoExportar", New Object() {dsxo, res, pruta, psociedad})
            res = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoExportar(ByVal dsxo As System.Data.DataSet, ByVal res As String, ByVal pruta As String, ByVal psociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoExportar", New Object() {dsxo, res, pruta, psociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoExportar(ByVal asyncResult As System.IAsyncResult, ByRef res As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            res = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/escribirArchivo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function escribirArchivo(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal f() As Byte, ByVal fileName As String, ByVal pruta As String) As String
            Dim results() As Object = Me.Invoke("escribirArchivo", New Object() {f, fileName, pruta})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginescribirArchivo(ByVal f() As Byte, ByVal fileName As String, ByVal pruta As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("escribirArchivo", New Object() {f, fileName, pruta}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndescribirArchivo(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoFun_ClienteNuevo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoFun_ClienteNuevo(ByVal dsxo As System.Data.DataSet, ByRef res As String, ByVal pruta As String, ByVal psociedad As String) As ServiceHollaBack
            Dim results() As Object = Me.Invoke("xoFun_ClienteNuevo", New Object() {dsxo, res, pruta, psociedad})
            res = CType(results(1),String)
            Return CType(results(0),ServiceHollaBack)
        End Function
        
        '''<remarks/>
        Public Function BeginxoFun_ClienteNuevo(ByVal dsxo As System.Data.DataSet, ByVal res As String, ByVal pruta As String, ByVal psociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoFun_ClienteNuevo", New Object() {dsxo, res, pruta, psociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoFun_ClienteNuevo(ByVal asyncResult As System.IAsyncResult, ByRef res As String) As ServiceHollaBack
            Dim results() As Object = Me.EndInvoke(asyncResult)
            res = CType(results(1),String)
            Return CType(results(0),ServiceHollaBack)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoFun_correlativoSAP", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoFun_correlativoSAP(ByVal dsxo As System.Data.DataSet) As Boolean
            Dim results() As Object = Me.Invoke("xoFun_correlativoSAP", New Object() {dsxo})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginxoFun_correlativoSAP(ByVal dsxo As System.Data.DataSet, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoFun_correlativoSAP", New Object() {dsxo}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoFun_correlativoSAP(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoFun_Resolucion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoFun_Resolucion(ByVal dtExport As System.Data.DataTable, ByRef zText As String) As Boolean
            Dim results() As Object = Me.Invoke("xoFun_Resolucion", New Object() {dtExport, zText})
            zText = CType(results(1),String)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginxoFun_Resolucion(ByVal dtExport As System.Data.DataTable, ByVal zText As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoFun_Resolucion", New Object() {dtExport, zText}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoFun_Resolucion(ByVal asyncResult As System.IAsyncResult, ByRef zText As String) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            zText = CType(results(1),String)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoFun_Workflow", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoFun_Workflow(ByVal dtExport As System.Data.DataTable, ByRef zText As String) As Boolean
            Dim results() As Object = Me.Invoke("xoFun_Workflow", New Object() {dtExport, zText})
            zText = CType(results(1),String)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginxoFun_Workflow(ByVal dtExport As System.Data.DataTable, ByVal zText As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoFun_Workflow", New Object() {dtExport, zText}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoFun_Workflow(ByVal asyncResult As System.IAsyncResult, ByRef zText As String) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            zText = CType(results(1),String)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetAsignaViasPago", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetAsignaViasPago(ByVal pruta As String, ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetAsignaViasPago", New Object() {pruta, sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetAsignaViasPago(ByVal pruta As String, ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetAsignaViasPago", New Object() {pruta, sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetAsignaViasPago(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetDeptos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetDeptos(ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetDeptos", New Object() {sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetDeptos(ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetDeptos", New Object() {sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetDeptos(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetAsignaViasPago_2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetAsignaViasPago_2(ByVal pruta As String, ByVal sociedad As String, ByVal fechaDespacho As Date) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetAsignaViasPago_2", New Object() {pruta, sociedad, fechaDespacho})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetAsignaViasPago_2(ByVal pruta As String, ByVal sociedad As String, ByVal fechaDespacho As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetAsignaViasPago_2", New Object() {pruta, sociedad, fechaDespacho}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetAsignaViasPago_2(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetBoom", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetBoom() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetBoom", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetBoom(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetBoom", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetBoom(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetBoom_", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetBoom_(ByVal pruta As String, ByVal psociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetBoom_", New Object() {pruta, psociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetBoom_(ByVal pruta As String, ByVal psociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetBoom_", New Object() {pruta, psociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetBoom_(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetCentro", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetCentro(ByVal pruta As String, ByVal sociedad As String, ByVal fechaCarga As Date) As String
            Dim results() As Object = Me.Invoke("xoGetCentro", New Object() {pruta, sociedad, fechaCarga})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetCentro(ByVal pruta As String, ByVal sociedad As String, ByVal fechaCarga As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetCentro", New Object() {pruta, sociedad, fechaCarga}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetCentro(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetCentroPv", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetCentroPv(ByVal pruta As String, ByVal sociedad As String, ByVal fechaCarga As Date) As String
            Dim results() As Object = Me.Invoke("xoGetCentroPv", New Object() {pruta, sociedad, fechaCarga})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetCentroPv(ByVal pruta As String, ByVal sociedad As String, ByVal fechaCarga As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetCentroPv", New Object() {pruta, sociedad, fechaCarga}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetCentroPv(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetClusterSegmentacion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetClusterSegmentacion(ByVal sociedad As String, ByVal pruta As String, ByVal fechaCarga As Date) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetClusterSegmentacion", New Object() {sociedad, pruta, fechaCarga})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetClusterSegmentacion(ByVal sociedad As String, ByVal pruta As String, ByVal fechaCarga As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetClusterSegmentacion", New Object() {sociedad, pruta, fechaCarga}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetClusterSegmentacion(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetCarga2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetCarga2(ByVal pruta As String, ByVal sociedad As String, ByVal fechaCarga As Date) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetCarga2", New Object() {pruta, sociedad, fechaCarga})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetCarga2(ByVal pruta As String, ByVal sociedad As String, ByVal fechaCarga As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetCarga2", New Object() {pruta, sociedad, fechaCarga}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetCarga2(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetCarga", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetCarga(ByVal pruta As String, ByVal sociedad As String, ByVal fechaCarga As Date) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetCarga", New Object() {pruta, sociedad, fechaCarga})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetCarga(ByVal pruta As String, ByVal sociedad As String, ByVal fechaCarga As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetCarga", New Object() {pruta, sociedad, fechaCarga}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetCarga(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetCarga3", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetCarga3(ByVal pruta As String, ByVal sociedad As String, ByVal fechaCarga As Date) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetCarga3", New Object() {pruta, sociedad, fechaCarga})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetCarga3(ByVal pruta As String, ByVal sociedad As String, ByVal fechaCarga As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetCarga3", New Object() {pruta, sociedad, fechaCarga}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetCarga3(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetClientes", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetClientes(ByVal pruta As String, ByVal sociedad As String, ByVal fechaDespacho As Date) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetClientes", New Object() {pruta, sociedad, fechaDespacho})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetClientes(ByVal pruta As String, ByVal sociedad As String, ByVal fechaDespacho As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetClientes", New Object() {pruta, sociedad, fechaDespacho}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetClientes(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetCuentaPorCobrar", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetCuentaPorCobrar(ByVal pruta As String, ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetCuentaPorCobrar", New Object() {pruta, sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetCuentaPorCobrar(ByVal pruta As String, ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetCuentaPorCobrar", New Object() {pruta, sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetCuentaPorCobrar(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetCuentaPorCobrar2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetCuentaPorCobrar2(ByVal pruta As String, ByVal sociedad As String, ByVal fecha As Date) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetCuentaPorCobrar2", New Object() {pruta, sociedad, fecha})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetCuentaPorCobrar2(ByVal pruta As String, ByVal sociedad As String, ByVal fecha As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetCuentaPorCobrar2", New Object() {pruta, sociedad, fecha}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetCuentaPorCobrar2(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetDespachos_2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetDespachos_2(ByVal pruta As String, ByVal sociedad As String, ByVal fechaCarga As Date) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetDespachos_2", New Object() {pruta, sociedad, fechaCarga})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetDespachos_2(ByVal pruta As String, ByVal sociedad As String, ByVal fechaCarga As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetDespachos_2", New Object() {pruta, sociedad, fechaCarga}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetDespachos_2(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetEncuesta", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetEncuesta(ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetEncuesta", New Object() {sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetEncuesta(ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetEncuesta", New Object() {sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetEncuesta(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetFel", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetFel(ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetFel", New Object() {sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetFel(ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetFel", New Object() {sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetFel(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetFel2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetFel2(ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetFel2", New Object() {sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetFel2(ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetFel2", New Object() {sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetFel2(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetFormasPago", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetFormasPago() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetFormasPago", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetFormasPago(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetFormasPago", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetFormasPago(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetRango", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetRango() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetRango", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetRango(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetRango", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetRango(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetLockMateriales", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetLockMateriales(ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetLockMateriales", New Object() {sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetLockMateriales(ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetLockMateriales", New Object() {sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetLockMateriales(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetMateriales", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetMateriales(ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetMateriales", New Object() {sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetMateriales(ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetMateriales", New Object() {sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetMateriales(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetMateriales2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetMateriales2(ByVal sociedad As String, ByVal pruta As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetMateriales2", New Object() {sociedad, pruta})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetMateriales2(ByVal sociedad As String, ByVal pruta As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetMateriales2", New Object() {sociedad, pruta}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetMateriales2(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetMarkers", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetMarkers(ByVal pSociedad As String, ByVal pFecha As Date, ByVal pOficina As String, ByVal pGrupov As String, ByVal pRuta As String) As ServiceHollaBack
            Dim results() As Object = Me.Invoke("xoGetMarkers", New Object() {pSociedad, pFecha, pOficina, pGrupov, pRuta})
            Return CType(results(0),ServiceHollaBack)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetMarkers(ByVal pSociedad As String, ByVal pFecha As Date, ByVal pOficina As String, ByVal pGrupov As String, ByVal pRuta As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetMarkers", New Object() {pSociedad, pFecha, pOficina, pGrupov, pRuta}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetMarkers(ByVal asyncResult As System.IAsyncResult) As ServiceHollaBack
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ServiceHollaBack)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetPreciosDescuentos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetPreciosDescuentos(ByVal pruta As String, ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetPreciosDescuentos", New Object() {pruta, sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetPreciosDescuentos(ByVal pruta As String, ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetPreciosDescuentos", New Object() {pruta, sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetPreciosDescuentos(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetDiaVisita", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetDiaVisita() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetDiaVisita", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetDiaVisita(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetDiaVisita", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetDiaVisita(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetPrecios", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetPrecios(ByVal pruta As String, ByVal sociedad As String, ByVal isMultilista As String, ByVal fechaCarga As Date) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetPrecios", New Object() {pruta, sociedad, isMultilista, fechaCarga})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetPrecios(ByVal pruta As String, ByVal sociedad As String, ByVal isMultilista As String, ByVal fechaCarga As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetPrecios", New Object() {pruta, sociedad, isMultilista, fechaCarga}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetPrecios(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetPreguntasInicialesFinales", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetPreguntasInicialesFinales(ByVal ruta As String, ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetPreguntasInicialesFinales", New Object() {ruta, sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetPreguntasInicialesFinales(ByVal ruta As String, ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetPreguntasInicialesFinales", New Object() {ruta, sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetPreguntasInicialesFinales(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetResolucionesSapHH", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetResolucionesSapHH(ByVal ruta As String, ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetResolucionesSapHH", New Object() {ruta, sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetResolucionesSapHH(ByVal ruta As String, ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetResolucionesSapHH", New Object() {ruta, sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetResolucionesSapHH(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetRazonesNV", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetRazonesNV() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetRazonesNV", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetRazonesNV(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetRazonesNV", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetRazonesNV(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetRuta", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetRuta(ByVal pruta As String, ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetRuta", New Object() {pruta, sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetRuta(ByVal pruta As String, ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetRuta", New Object() {pruta, sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetRuta(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetContingenciaImp", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetContingenciaImp(ByVal pruta As String, ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetContingenciaImp", New Object() {pruta, sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetContingenciaImp(ByVal pruta As String, ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetContingenciaImp", New Object() {pruta, sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetContingenciaImp(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetTipos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetTipos(ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetTipos", New Object() {sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetTipos(ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetTipos", New Object() {sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetTipos(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetUsuarios", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetUsuarios(ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetUsuarios", New Object() {sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetUsuarios(ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetUsuarios", New Object() {sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetUsuarios(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetWorkflowSAPHH", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetWorkflowSAPHH(ByVal idRuta As String, ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetWorkflowSAPHH", New Object() {idRuta, sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetWorkflowSAPHH(ByVal idRuta As String, ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetWorkflowSAPHH", New Object() {idRuta, sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetWorkflowSAPHH(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetWorkflowGiro", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetWorkflowGiro(ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetWorkflowGiro", New Object() {sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetWorkflowGiro(ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetWorkflowGiro", New Object() {sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetWorkflowGiro(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetPresupuestoCliente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetPresupuestoCliente(ByVal sociedad As String, ByVal ruta As String, ByVal fecha As Date) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetPresupuestoCliente", New Object() {sociedad, ruta, fecha})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetPresupuestoCliente(ByVal sociedad As String, ByVal ruta As String, ByVal fecha As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetPresupuestoCliente", New Object() {sociedad, ruta, fecha}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetPresupuestoCliente(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetHistorial", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetHistorial(ByVal idruta As String, ByVal fecha As Date, ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetHistorial", New Object() {idruta, fecha, sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetHistorial(ByVal idruta As String, ByVal fecha As Date, ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetHistorial", New Object() {idruta, fecha, sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetHistorial(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetResolucionSAP", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetResolucionSAP(ByRef zText As String, ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetResolucionSAP", New Object() {zText, sociedad})
            zText = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetResolucionSAP(ByVal zText As String, ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetResolucionSAP", New Object() {zText, sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetResolucionSAP(ByVal asyncResult As System.IAsyncResult, ByRef zText As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            zText = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetResolucionSAPB", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetResolucionSAPB(ByRef zText As String, ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetResolucionSAPB", New Object() {zText, sociedad})
            zText = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetResolucionSAPB(ByVal zText As String, ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetResolucionSAPB", New Object() {zText, sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetResolucionSAPB(ByVal asyncResult As System.IAsyncResult, ByRef zText As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            zText = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetResolucionSAP2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetResolucionSAP2(ByRef zText As String, ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetResolucionSAP2", New Object() {zText, sociedad})
            zText = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetResolucionSAP2(ByVal zText As String, ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetResolucionSAP2", New Object() {zText, sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetResolucionSAP2(ByVal asyncResult As System.IAsyncResult, ByRef zText As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            zText = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/xoGetWorkflowSAP", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function xoGetWorkflowSAP(ByVal idRuta As String, ByVal sociedad As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("xoGetWorkflowSAP", New Object() {idRuta, sociedad})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginxoGetWorkflowSAP(ByVal idRuta As String, ByVal sociedad As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("xoGetWorkflowSAP", New Object() {idRuta, sociedad}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndxoGetWorkflowSAP(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ServiceHollaBack
        
        Private resultadoField As Boolean
        
        Private mensajeField As String
        
        Private deField As String
        
        Private paraField As String
        
        Private datosField As System.Data.DataSet
        
        '''<remarks/>
        Public Property resultado() As Boolean
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property de() As String
            Get
                Return Me.deField
            End Get
            Set
                Me.deField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property para() As String
            Get
                Return Me.paraField
            End Get
            Set
                Me.paraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property datos() As System.Data.DataSet
            Get
                Return Me.datosField
            End Get
            Set
                Me.datosField = value
            End Set
        End Property
    End Class
End Namespace
